### ISSUE TITLE
do you plan to continue development of this project?

### ISSUE THREAD

**Issue by soops** [trmml/textymous#6]
I could always help out if you'd like, I'm interested in something like this to test out some Ruby backend type stuff.

**Comment by trmml** [comment]
@soops At some point I'd love to start it up again but it's been a while and finding a good SMS API is trouble. It'd be awesome if you wanted to start working on it, though. The mess lives entirely in [app/controllers/twilio_controller.rb](https://github.com/trmml/textymous/blob/master/app/controllers/twilio_controller.rb)

**Comment by trmml** [comment]
@soops Let's boot this shit back up at CodeDay.
